version: "3.8"

services:
  db:
    image: docker.io/library/mysql:8.0
    container_name: daftar-tugas-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-daftar_tugas}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro,Z
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: Containerfile
    container_name: daftar-tugas-backend
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER:-app}
      DB_PASSWORD: ${MYSQL_PASSWORD:-secret}
      DB_NAME: ${MYSQL_DATABASE:-daftar_tugas}
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db-data: {}
